In [1]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [4]:
v = CountVectorizer(ngram_range=(1,3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

In [5]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [6]:
import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm") 

def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)
    
    return " ".join(filtered_tokens)

In [7]:

preprocess("Thor ate pizza")

'thor eat pizza'

In [8]:
corpus_processed = [
    preprocess(text) for text in corpus
]
corpus_processed

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [9]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(corpus_processed)
v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [11]:
v.transform(['thor eat pizza']).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [12]:
v.transform(['Hulk eat pizza']).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]])

In [17]:
import pandas as pd

df = pd.read_json('News_Category_Dataset.json', lines=True)
print(df.shape)

df.head()

(124989, 6)

,short_description,headline,date,link,authors,category
0,She left her husband. He killed their children...,There Were 2 Mass Shootings In Texas Last Week...,2018-05-26,https://www.huffingtonpost.com/entry/texas-ama...,Melissa Jeltsen,CRIME
1,Of course it has a song.,Will Smith Joins Diplo And Nicky Jam For The 2...,2018-05-26,https://www.huffingtonpost.com/entry/will-smit...,Andy McDonald,ENTERTAINMENT
2,The actor and his longtime girlfriend Anna Ebe...,Hugh Grant Marries For The First Time At Age 57,2018-05-26,https://www.huffingtonpost.com/entry/hugh-gran...,Ron Dicker,ENTERTAINMENT
3,The actor gives Dems an ass-kicking for not fi...,Jim Carrey Blasts 'Castrato' Adam Schiff And D...,2018-05-26,https://www.huffingtonpost.com/entry/jim-carre...,Ron Dicker,ENTERTAINMENT
4,"The ""Dietland"" actress said using the bags is ...",Julianna Margulies Uses Donald Trump Poop Bags...,2018-05-26,https://www.huffingtonpost.com/entry/julianna-...,Ron Dicker,ENTERTAINMENT

In [18]:
cates = df.groupby('category')
print("total categories:", cates.ngroups)
print(cates.size())

total categories: 31
category
ARTS               1509
ARTS & CULTURE     1339
BLACK VOICES       3858
BUSINESS           4254
COLLEGE            1144
COMEDY             3971
CRIME              2893
EDUCATION          1004
ENTERTAINMENT     14257
FIFTY              1401
GOOD NEWS          1398
GREEN              2622
HEALTHY LIVING     6694
IMPACT             2602
LATINO VOICES      1129
MEDIA              2815
PARENTS            3955
POLITICS          32739
QUEER VOICES       4995
RELIGION           2556
SCIENCE            1381
SPORTS             4167
STYLE              2254
TASTE              2096
TECH               1231
THE WORLDPOST      3664
TRAVEL             2145
WEIRD NEWS         2670
WOMEN              3490
WORLD NEWS         2177
WORLDPOST          2579
dtype: int64

In [22]:
min(cates.size())

1004

In [26]:
min_sample = 1004

df_bussiness = df[df.category=="BUSINESS"].sample(min_sample, random_state=2022)
df_bussiness

,short_description,headline,date,link,authors,category
120663,Conscious awareness of the comfort principle i...,Obstacles for Women in Business: The Comfort P...,2014-06-08,https://www.huffingtonpost.com/entry/obstacles...,"Caroline Turner, ContributorAuthor, workshop f...",BUSINESS
57531,,5 Business Lessons You Can Learn from Fitness ...,2016-05-29,https://www.huffingtonpost.com/entry/5-busines...,"AJ Agrawal, Contributor",BUSINESS
61632,Other regulators are stepping up while the SEC...,Obama’s Wall Street Watchdog Does Little To Pr...,2016-04-12,https://www.huffingtonpost.com/entry/barack-ob...,Shahien Nasiripour,BUSINESS
13088,"Men run everything, and it's enough already. W...",The Lack Of Women Leaders Is A National Emergency,2017-10-28,https://www.huffingtonpost.com/entry/women-lea...,Emily Peck,BUSINESS
80943,The stand-out national problem we have today i...,Profit Sharing: Labor's New Opportunity,2015-09-06,https://www.huffingtonpost.com/entry/profit-sh...,"Joseph Blasi, ContributorJ. Robert Beyster Dis...",BUSINESS
...,...,...,...,...,...,...
122995,American hotel workers are not highly paid to ...,Why Calls for Boycotts Always Hurt The Wrong P...,2014-05-12,https://www.huffingtonpost.com/entry/why-calls...,"Lynda Bekore, ContributorContent Director, Tar...",BUSINESS
73162,Bringing up its financial ties to the school w...,Exxon Mobil Screwed Up Its Attack On Columbia ...,2015-12-02,https://www.huffingtonpost.com/entry/exxon-mob...,Lydia O'Connor,BUSINESS
110387,Progress is important to growing your business...,How to Make Daily Progress in Your Business,2014-10-03,https://www.huffingtonpost.com/entry/how-to-ma...,"Stacia Pierce, ContributorLife coach, career e...",BUSINESS
114763,"While franchising isn't an easy task, the trut...",The Essential Guide to Preparing to Franchise ...,2014-08-14,https://www.huffingtonpost.com/entry/the-essen...,"Bob Steinberger, ContributorBusiness lawyer, f...",BUSINESS
105678,,How Has Women's Entrepreneurship Day Made a Re...,2014-11-26,https://www.huffingtonpost.com/entry/how-has-w...,"Laura Dunn, ContributorSocial Media and Commun...",BUSINESS

In [35]:
category = {c for c in df.category}
category

{'ARTS',
 'ARTS & CULTURE',
 'BLACK VOICES',
 'BUSINESS',
 'COLLEGE',
 'COMEDY',
 'CRIME',
 'EDUCATION',
 'ENTERTAINMENT',
 'FIFTY',
 'GOOD NEWS',
 'GREEN',
 'HEALTHY LIVING',
 'IMPACT',
 'LATINO VOICES',
 'MEDIA',
 'PARENTS',
 'POLITICS',
 'QUEER VOICES',
 'RELIGION',
 'SCIENCE',
 'SPORTS',
 'STYLE',
 'TASTE',
 'TECH',
 'THE WORLDPOST',
 'TRAVEL',
 'WEIRD NEWS',
 'WOMEN',
 'WORLD NEWS',
 'WORLDPOST'}

In [36]:
df_cate = []
for catte in category:
    df_cate.append(df[df.category==catte].sample(min_sample, random_state=2022))

In [37]:
df_cate

[                                        short_description  \
 121346
 107716  There is a solid base of evidence that we can ...
 120348  Lengthening the tenure decision process from t...
 98572   Technology has become further integrated into ...
 93193   Hillary Clinton may need to school herself a b...
 ...                                                   ...
 103016  Aphorisms are an excellent way of encouraging ...
 98460   It has never been easier to learn. Formal and ...
 24855   By Jane Meredith Adams About 24 hours after a ...
 30053   By Linda K. Wertheimer Dropping a handout with...
 117883  How do we act on new information, when our sys...

                                                  headline       date  \
 121346    High School Dropout Rate: Solutions for Success 2014-06-01
 107716                         Can We Learn to Get Along? 2014-11-02
 120348  Vergara v. California Decision: Teacher Tenure... 2014-06-12
 98572   The Global Search for Education: The Tech Repo... 2015-02-16
 93193              Hillary Clinton Feels Common Core Pain 2015-04-19
 ...                                                   ...        ...
 103016  Teaching the Bible as Literature in Public Hig... 2014-12-27
 98460   Parents, Share Your Story: How Do You Empower ... 2015-02-17
 24855   California Law Spurs Reforms After High School... 2017-06-05
 30053                            The Alt-Right Curriculum 2017-04-06
 117883  In Order for Our Kids to Keep Learning, We Nee... 2014-07-10

                                                      link  \
 121346  https://www.huffingtonpost.com/entry/high-scho...
 107716  https://www.huffingtonpost.com/entry/can-we-le...
 120348  https://www.huffingtonpost.com/entry/vergara-v...
 98572   https://www.huffingtonpost.com/entry/the-globa...
 93193   https://www.huffingtonpost.com/entry/hillary-c...
 ...                                                   ...
 103016  https://www.huffingtonpost.com/entry/teaching-...
 98460   https://www.huffingtonpost.com/entry/parents-s...
 24855   https://www.huffingtonpost.com/entry/californi...
 30053   https://www.huffingtonpost.com/entry/the-alt-r...
 117883  https://www.huffingtonpost.com/entry/in-order-...

                                                   authors   category
 121346  Matthew Lynch, Ed.D., ContributorAuthor of The...  EDUCATION
 107716  Fernando Reimers, ContributorAcademic and Advi...  EDUCATION
 120348  Erin Simmeth, ContributorPublic school teacher...  EDUCATION
 98572   C. M. Rubin, ContributorBlogger and author, 'T...  EDUCATION
 93193   Anthony Cody, ContributorCo-Founder, Network f...  EDUCATION
 ...                                                   ...        ...
 103016  Frank Breslin, ContributorRetired high-school ...  EDUCATION
 98460   Smart Parents, ContributorA blog series for pa...  EDUCATION
 24855   EdSource, ContributorNonprofit news site focus...  EDUCATION
 30053   The Atlantic, ContributorExploring the America...  EDUCATION
 117883  Jennifer Peck, ContributorExecutive Director, ...  EDUCATION

 [1004 rows x 6 columns],
                                         short_description  \
 4373    If it goes ahead, the facility will operate ar...
 96040   With all the evidence and examples of how earl...
 122218  The lack of diversity in children's literature...
 112702  Two days after September, 11, 2001, still daze...
 101259  One in five children--a full fifth of the worl...
 ...                                                   ...
 109893  As the world's social and environmental challe...
 80417   Jacqueline is an inspiration to anyone with a ...
 105142  On World AIDS Day in 2012, the New York City-b...
 113827
 91638   I met a great lady last week. The Grandest of ...

                                                  headline       date  \
 4373    ‘Our Bodies Can’t Take That Kind Of Damage’: T... 2018-03-07
 96040              Why Music: The Secret Sauce of Success 2015-03-17
 122218  Diversity in Children's Books: Moving From Out... 2014-05-21
 112702                                 September 11, 2001 2014-09-06
 101259  Connection Through Captivation: The Art of Vac... 2015-01-16
 ...                                                   ...        ...
 109893  A New Approach to Profits: Creating Shared Val... 2014-10-09
 80417   From a Refugee Camp to a Royal Court:  A Cambo... 2015-09-12
 105142              An AIDS Quilt Songbook: Sing for Hope 2014-12-02
 113827  Indian Male Rickshaw Drivers Playing Key Role ... 2014-08-24
 91638          Finding a Soulmate on the New Madrid Fault 2015-05-07

                                                      link  \
 4373    https://www.huffingtonpost.com/entry/vallejo-c...
 96040   https://www.huffingtonpost.com/entry/why-music...
 122218  https://www.huffingtonpost.com/entry/diversity...
 112702  https://www.huffingtonpost.com/entry/september...
 101259  https://www.huffingtonpost.com/entry/connectio...
 ...                                                   ...
 109893  https://www.huffingtonpost.com/entry/a-new-app...
 80417   https://www.huffingtonpost.com/entry/from-a-re...
 105142  https://www.huffingtonpost.com/entry/post_8657...
 113827  https://www.huffingtonpost.com/entry/maternal-...
 91638   https://www.huffingtonpost.com/entry/finding-m...

                                                   authors category
 4373             Melissa Hung, On assignment for HuffPost   IMPACT
 96040   Frank Fitzpatrick, ContributorMulti-Platinum r...   IMPACT
 122218  Kyle Zimmer, ContributorPresident and CEO,  Fi...   IMPACT
 112702  Vicki Cobb, ContributorPresident and founder o...   IMPACT
 101259  Dr. Orin Levine, ContributorDirector of Vaccin...   IMPACT
 ...                                                   ...      ...
 109893  Mukhisa Kituyi, ContributorSecretary-General, ...   IMPACT
 80417   Steve Mariotti, ContributorFounder of Network ...   IMPACT
 105142  Camille Zamora, ContributorSoprano, Co-Founder...   IMPACT
 113827                                   Eleanor Goldberg   IMPACT
 91638   Georgianne Nienaber, ContributorWriter and author   IMPACT

 [1004 rows x 6 columns],
                                         short_description  \
 42813         This doesn’t affect me like it affects you.
 68620   New York Times pundit Tom Friedman apparently ...
 62866   Not to freak you out, but ... we're all about ...
 73126   On Thursday, Reid will introduce a gun control...
 29606   The innovation group should measure the effect...
 ...                                                   ...
 82658   After expressing an eagerness to weigh in more...
 73464   The Center for Medical Progress, which release...
 5449    Democratic efforts to offset the lost state ta...
 11813   Rep. Jackie Speier (D-Calif.) has been an outs...
 114897

                                                  headline       date  \
 42813     A Letter From A Straight, White Male: I'm Sorry 2016-11-11
 68620   What Super Wealthy Times Columnist Tom Friedma... 2016-01-23
 62866   Tinder Now Lets You Swipe Right For The Presid... 2016-03-28
 73126   Harry Reid On San Bernardino Shooting: 'This M... 2015-12-02
 29606   A Blueprint For Trump's White House Office Of ... 2017-04-11
 ...                                                   ...        ...
 82658   Ben Carson Suggests Obama’s Iran Deal Is ‘Anti... 2015-08-17
 73464   Anti-Abortion Groups Condemn Colorado Springs ... 2015-11-28
 5449    It Won't Be Easy For Blue States To Dodge The ... 2018-02-17
 11813   Congresswoman Says At Least 2 Members Of Congr... 2017-11-14
 114897   How One Member Of Congress Gets Away From It All 2014-08-12

                                                      link  \
 42813   https://www.huffingtonpost.com/entry/a-letter-...
 68620   https://www.huffingtonpost.com/entry/someone-g...
 62866   https://www.huffingtonpost.comhttp://pubx.co/J...
 73126   https://www.huffingtonpost.com/entry/harry-rei...
 29606   https://www.huffingtonpost.com/entry/a-bluepri...
 ...                                                   ...
 82658   https://www.huffingtonpost.comhttp://thinkprog...
 73464   https://www.huffingtonpost.com/entry/colorado-...
 5449    https://www.huffingtonpost.com/entry/gop-tax-l...
 11813   https://www.huffingtonpost.com/entry/speier-se...
 114897  https://www.huffingtonpost.com/entry/hakeem-je...

                                                   authors  category
 42813   Zachary Volosky, ContributorStudent, blogger, ...  POLITICS
 68620   Peter Dreier, ContributorE.P. Clapp Distinguis...  POLITICS
 62866                                                      POLITICS
 73126                                         Marina Fang  POLITICS
 29606   Anthony Figliola, ContributorPolicy Expert and...  POLITICS
 ...                                                   ...       ...
 82658                                                      POLITICS
 73464                                          Sam Levine  POLITICS
 5449                     Arthur Delaney and Daniel Marans  POLITICS
 11813                                       Amanda Terkel  POLITICS
 114897                                        Matt Sledge  POLITICS

 [1004 rows x 6 columns],
                                         short_description  \
 85080   The basic chemistry of wine flavors, colors, a...
 122455
 79720   Scientists say they have successfully tested a...
 9859                            Just don't tell the kids.
 123989
 ...                                                   ...
 81556   "I have loved and been loved; I have been give...
 101594  It's been many years since I have trusted anyt...
 80372                This thing is a star-making machine.
 46246   The luminous flashes last only milliseconds an...
 92882

                                                  headline       date  \
 85080   This Wine Chemistry Video Explains What Connoi... 2015-07-21
 122455              SOLVED? Massive Magnetic Star Mystery 2014-05-18
 79720   Invisibility Cloak May Be Moving Closer To Rea... 2015-09-20
 9859    Oxford Researchers Make Startling Discovery Ab... 2017-12-11
 123989  WATCH: Here's A Cool Trick To Help You See Wit... 2014-04-30
 ...                                                   ...        ...
 81556    Oliver Sacks, Neurologist And Author, Dies At 82 2015-08-30
 101594       The Crisis of Confidence in Medical Research 2015-01-12
 80372   Starry-Eyed Scientists Discover 'Beast Of A Ga... 2015-09-12
 46246   Rare Photo Captures Sprites, Gravity Waves Ove... 2016-10-04
 92882   Mindfulness Therapy May Help Prevent Depressio... 2015-04-23

                                                      link  \
 85080   https://www.huffingtonpost.com/entry/the-chemi...
 122455  https://www.huffingtonpost.com/entry/magnetar-...
 79720   https://www.huffingtonpost.com/entry/invisibil...
 9859    https://www.huffingtonpost.com/entry/oxford-re...
 123989  https://www.huffingtonpost.com/entry/see-witho...
 ...                                                   ...
 81556   https://www.huffingtonpost.com/entry/oliver-sa...
 101594  https://www.huffingtonpost.com/entry/the-crisi...
 80372   https://www.huffingtonpost.com/entry/newly-dis...
 46246   https://www.huffingtonpost.com/entry/sprites-s...
 92882   https://www.huffingtonpost.com/entry/depressio...

                                                   authors category
 85080                                 Eliza Sankar-Gorton  SCIENCE
 122455                                  Jacqueline Howard  SCIENCE
 79720                                Will Dunham, Reuters  SCIENCE
 9859                                      Carol Kuruvilla  SCIENCE
 123989                                         Ron Dicker  SCIENCE
 ...                                                   ...      ...
 81556                                     Melissa Jeltsen  SCIENCE
 101594  Allen Frances, ContributorProfessor Emeritus, ...  SCIENCE
 80372                                      Chris D'Angelo  SCIENCE
 46246                                      Nina Golgowski  SCIENCE
 92882                                    Carolyn Gregoire  SCIENCE

 [1004 rows x 6 columns],
                                         short_description  \
 17715   The Secretary of State will shrink the Office ...
 107734
 98627
 55156
 10442   We live in contradictory and confusing times: ...
 ...                                                   ...
 5255    He believed that all men were lost and would f...
 92765   The question I'm asking is this: What possible...
 17977   A few weeks ago, on a breezy Saturday evening,...
 109661
 84102          Lack of information is breeding confusion.

                                                  headline       date  \
 17715   Rex Tillerson's State Department Is Scrapping ... 2017-08-29
 107734                 These Nuns Are All About That Bass 2014-11-02
 98627          Meet Baton Rouge's Hip-Hop Catholic Priest 2015-02-15
 55156   Across Faith and Identities, NYC is Leading th... 2016-06-25
 10442                      A Star of the Abrahamic Faiths 2017-12-03
 ...                                                   ...        ...
 5255    Billy Graham, 'America's Pastor' And Noted Eva... 2018-02-21
 92765   Saving a Murderer's Life: Who Would Jesus Exec... 2015-04-24
 17977                            Coming Out As An Atheist 2017-08-26
 109661  Israeli And Palestinian Teens Sing About 'Home... 2014-10-11
 84102   Philadelphia In A State Of Panic As Pope Visit... 2015-08-01

                                                      link  \
 17715   https://www.huffingtonpost.com/entry/tillerson...
 107734  https://www.huffingtonpost.com/entry/nuns-on-t...
 98627   https://www.huffingtonpost.com/entry/rapping-c...
 55156   https://www.huffingtonpost.com/entry/across-fa...
 10442   https://www.huffingtonpost.com/entry/a-star-of...
 ...                                                   ...
 5255    https://www.huffingtonpost.com/entry/billy-gra...
 92765   https://www.huffingtonpost.com/entry/saving-a-...
 17977   https://www.huffingtonpost.com/entry/coming-ou...
 109661  https://www.huffingtonpost.com/entry/ymca-jeru...
 84102   https://www.huffingtonpost.com/entry/philadelp...

                                                   authors  category
 17715   Rev. Dr. Mae Elise Cannon, ContributorAuthor. ...  RELIGION
 107734                                    Carol Kuruvilla  RELIGION
 98627                                                      RELIGION
 55156   Nisha Agarwal, ContributorCommissioner, NYC Ma...  RELIGION
 10442   Akbar Ahmed, ContributorChair of Islamic Studi...  RELIGION
 ...                                                   ...       ...
 5255                       Jade Walker and Nina Golgowski  RELIGION
 92765   Chris Boeskool, ContributorBlogs at theboeskoo...  RELIGION
 17977   Jasmine Jaksic, ContributorTechie, writer and ...  RELIGION
 109661                                    Carol Kuruvilla  RELIGION
 84102                  Michael R. Sisak, Associated Press  RELIGION

 [1004 rows x 6 columns],
                                         short_description  \
 106839  Having pulled the rug out from under the Hispa...
 35305                                 We need each other.
 94248   Senator, we may not always see eye-to-eye when...
 118413
 52319   Last year, a group of Central American and Mex...
 ...                                                   ...
 94679   I recently had the opportunity to speak with J...
 48966   “Living here in the United States, it seems li...
 82118                                        Ohhh, Romeo!
 18980                          "Video release party lit!"
 87594   There is a cruel irony to boycotting Dominican...

                                                  headline       date  \
 106839  Midterm Lesson for Democrats: Don't Take Latin... 2014-11-13
 35305   This Is Not A Time To Let A 'Who Has It Worse'... 2017-02-04
 94248               Open Letter to Sen. Rafael (Ted) Cruz 2015-04-07
 118413              World Cup Photo Diary: My Day in Lapa 2014-07-04
 52319   Texas, Facing A Lawsuit, Makes It Easier For U... 2016-07-27
 ...                                                   ...        ...
 94679   A Way of Life: Juan Palma's Leadership on Publ... 2015-04-02
 48966   These Latinos Nail Why U.S. Citizens Aren’t Th... 2016-09-02
 82118   John Leguizamo Recites Romeo's Monologue As A ... 2015-08-24
 18980   This Photo Of Bruno Mars Celebrating 'Versace ... 2017-08-14
 87594   The problem with boycotting the Dominican Repu... 2015-06-22

                                                      link  \
 106839  https://www.huffingtonpost.com/entry/midterm-l...
 35305   https://www.huffingtonpost.com/entry/this-is-n...
 94248   https://www.huffingtonpost.com/entry/open-lett...
 118413  https://www.huffingtonpost.com/entry/world-cup...
 52319   https://www.huffingtonpost.comhttp://www.latim...
 ...                                                   ...
 94679   https://www.huffingtonpost.com/entry/a-way-of-...
 48966   https://www.huffingtonpost.com/entry/these-lat...
 82118   https://www.huffingtonpost.com/entry/john-legu...
 18980   https://www.huffingtonpost.com/entry/this-phot...
 87594   https://www.huffingtonpost.com/entry/the-probl...

                                                   authors       category
 106839  NCLR Action Fund, ContributorWorking to empowe...  LATINO VOICES
 35305   Julissa Arce, ContributorImmigrant Rights Advo...  LATINO VOICES
 94248   NCLR Action Fund, ContributorWorking to empowe...  LATINO VOICES
 118413  Raul de Molina, ContributorTelevision host, au...  LATINO VOICES
 52319                                                      LATINO VOICES
 ...                                                   ...            ...
 94679   Rod Torrez, ContributorLives in Northern New M...  LATINO VOICES
 48966                                Tanisha Love Ramirez  LATINO VOICES
 82118                                Tanisha Love Ramirez  LATINO VOICES
 18980                                     Carolina Moreno  LATINO VOICES
 87594   Moraima Capellán Pichardo, ContributorLatina |...  LATINO VOICES

 [1004 rows x 6 columns],
                                         short_description  \
 38126   Kids need doctors with special training before...
 91312
 113186  I have heard the nagging voice before, and I h...
 110712
 121144  As my years are folding one into the other, I ...
 ...                                                   ...
 124406
 99546   I am discovering the deep connections between ...
 65052   It's one of the best upper body workouts you c...
 116580
 101604  The #1 New Year's resolution is to lose weight...

                                                  headline       date  \
 38126   Millions Of Children Live Miles Away From Chil... 2017-01-04
 91312    Wheelchair Wisdom: I Am Connected to All of Life 2015-05-11
 113186  5 Options to the Nagging Voice in Your Head at... 2014-09-01
 110712  10 Things This Couple Learned When They Ditche... 2014-09-29
 121144                    The 'Rules' I Choose To Live By 2014-06-03
 ...                                                   ...        ...
 124406  Jon Kabat-Zinn: 'The Real Meditation Practice ... 2014-04-25
 99546                 Want Happiness? Practice Minimalism 2015-02-05
 65052                        How To Do The Perfect Pullup 2016-03-03
 116580              Superheroes Live in the Heart of Life 2014-07-25
 101604                    A Weighty New Year's Resolution 2015-01-12

                                                      link  \
 38126   https://www.huffingtonpost.com/entry/millions-...
 91312   https://www.huffingtonpost.com/entry/wheelchai...
 113186  https://www.huffingtonpost.com/entry/5-options...
 110712  https://www.huffingtonpost.com/entry/what-this...
 121144  https://www.huffingtonpost.com/entry/life-less...
 ...                                                   ...

In [39]:
df_balanced = pd.concat(df_cate,axis=0)
df_balanced.category.value_counts()

category
EDUCATION         1004
IMPACT            1004
POLITICS          1004
SCIENCE           1004
RELIGION          1004
LATINO VOICES     1004
HEALTHY LIVING    1004
STYLE             1004
ARTS & CULTURE    1004
ARTS              1004
PARENTS           1004
BLACK VOICES      1004
BUSINESS          1004
THE WORLDPOST     1004
GOOD NEWS         1004
TRAVEL            1004
MEDIA             1004
TECH              1004
GREEN             1004
COMEDY            1004
FIFTY             1004
QUEER VOICES      1004
WOMEN             1004
CRIME             1004
TASTE             1004
SPORTS            1004
WORLDPOST         1004
WEIRD NEWS        1004
WORLD NEWS        1004
ENTERTAINMENT     1004
COLLEGE           1004
Name: count, dtype: int64

In [42]:
df_balanced.sample()

,short_description,headline,date,link,authors,category
104501,The Yale Black Men's Union launched the To My ...,To My Unborn Son: Yale Black Men's Union Launc...,2014-12-09,https://www.huffingtonpost.com/entry/to-my-unb...,"Nicole Angela Tinson, ContributorPolicy, Advoc...",COLLEGE

In [43]:
category_map = {
    "EDUCATION": 0,
    "IMPACT": 1,
    "POLITICS": 2,
    "SCIENCE": 3,
    "RELIGION": 4,
    "LATINO VOICES": 5,
    "HEALTHY LIVING": 6,
    "STYLE": 7,
    "ARTS & CULTURE": 8,
    "ARTS": 9,
    "PARENTS": 10,
    "BLACK VOICES": 11,
    "BUSINESS": 12,
    "THE WORLDPOST": 13,
    "GOOD NEWS": 14,
    "TRAVEL": 15,
    "MEDIA": 16,
    "TECH": 17,
    "GREEN": 18,
    "COMEDY": 19,
    "FIFTY": 20,
    "QUEER VOICES": 21,
    "WOMEN": 22,
    "CRIME": 23,
    "TASTE": 24,
    "SPORTS": 25,
    "WORLDPOST": 26,
    "WEIRD NEWS": 27,
    "WORLD NEWS": 28,
    "ENTERTAINMENT": 29,
    "COLLEGE": 30
}

In [45]:
df_balanced['category_num'] = df_balanced.category.map(category_map)
df_balanced.head()

,short_description,headline,date,link,authors,category,category_num
121346,,High School Dropout Rate: Solutions for Success,2014-06-01,https://www.huffingtonpost.com/entry/high-scho...,"Matthew Lynch, Ed.D., ContributorAuthor of The...",EDUCATION,0
107716,There is a solid base of evidence that we can ...,Can We Learn to Get Along?,2014-11-02,https://www.huffingtonpost.com/entry/can-we-le...,"Fernando Reimers, ContributorAcademic and Advi...",EDUCATION,0
120348,Lengthening the tenure decision process from t...,Vergara v. California Decision: Teacher Tenure...,2014-06-12,https://www.huffingtonpost.com/entry/vergara-v...,"Erin Simmeth, ContributorPublic school teacher...",EDUCATION,0
98572,Technology has become further integrated into ...,The Global Search for Education: The Tech Repo...,2015-02-16,https://www.huffingtonpost.com/entry/the-globa...,"C. M. Rubin, ContributorBlogger and author, 'T...",EDUCATION,0
93193,Hillary Clinton may need to school herself a b...,Hillary Clinton Feels Common Core Pain,2015-04-19,https://www.huffingtonpost.com/entry/hillary-c...,"Anthony Cody, ContributorCo-Founder, Network f...",EDUCATION,0

In [47]:
df_balanced['text'] = df_balanced[['headline', 'short_description']].agg(' '.join, axis=1)
df_balanced.head()

,short_description,headline,date,link,authors,category,category_num,text
121346,,High School Dropout Rate: Solutions for Success,2014-06-01,https://www.huffingtonpost.com/entry/high-scho...,"Matthew Lynch, Ed.D., ContributorAuthor of The...",EDUCATION,0,High School Dropout Rate: Solutions for Success
107716,There is a solid base of evidence that we can ...,Can We Learn to Get Along?,2014-11-02,https://www.huffingtonpost.com/entry/can-we-le...,"Fernando Reimers, ContributorAcademic and Advi...",EDUCATION,0,Can We Learn to Get Along? There is a solid ba...
120348,Lengthening the tenure decision process from t...,Vergara v. California Decision: Teacher Tenure...,2014-06-12,https://www.huffingtonpost.com/entry/vergara-v...,"Erin Simmeth, ContributorPublic school teacher...",EDUCATION,0,Vergara v. California Decision: Teacher Tenure...
98572,Technology has become further integrated into ...,The Global Search for Education: The Tech Repo...,2015-02-16,https://www.huffingtonpost.com/entry/the-globa...,"C. M. Rubin, ContributorBlogger and author, 'T...",EDUCATION,0,The Global Search for Education: The Tech Repo...
93193,Hillary Clinton may need to school herself a b...,Hillary Clinton Feels Common Core Pain,2015-04-19,https://www.huffingtonpost.com/entry/hillary-c...,"Anthony Cody, ContributorCo-Founder, Network f...",EDUCATION,0,Hillary Clinton Feels Common Core Pain Hillary...

In [48]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    df_balanced.text,
    df_balanced.category_num,
    test_size=0.2,
    random_state=2022,
    stratify=df_balanced.category_num
)

In [49]:
print(x_train.shape)
x_train.head()

(24899,)

110995    Nearly 2 Million Americans Have Chlamydia, Est...
40375     1,000 Russian Athletes Benefited From Doping C...
32922     This Hilariously Real Video Might Put You Off ...
24456     Wonder Woman In The Age Of Trump When my darli...
89219     Why Jesus Would Say 'Black Lives Matter' Conti...
Name: text, dtype: object

In [51]:
y_test.value_counts()

category_num
5     201
19    201
22    201
9     201
29    201
28    201
23    201
0     201
11    201
25    201
10    201
17    201
24    201
8     201
16    201
13    201
27    201
26    201
15    201
2     201
6     201
21    201
3     201
18    201
1     201
14    200
30    200
4     200
7     200
20    200
12    200
Name: count, dtype: int64

In [73]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_bow', CountVectorizer(ngram_range = (1, 1))),        #using the ngram_range parameter 
     ('Multi NB', MultinomialNB())         
])

#2. fit with X_train and y_train
clf.fit(x_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(x_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.42      0.76      0.54       201
           1       0.23      0.45      0.31       201
           2       0.47      0.51      0.49       201
           3       0.72      0.40      0.51       201
           4       0.67      0.47      0.56       200
           5       0.63      0.39      0.48       201
           6       0.38      0.38      0.38       201
           7       0.78      0.37      0.50       200
           8       0.44      0.18      0.26       201
           9       0.46      0.48      0.47       201
          10       0.35      0.43      0.38       201
          11       0.44      0.33      0.38       201
          12       0.45      0.32      0.37       200
          13       0.44      0.37      0.40       201
          14       0.54      0.39      0.45       200
          15       0.53      0.56      0.55       201
          16       0.60      0.49      0.54       201
          17       0.71      0.45      0.55       201
          18       0.52      0.45      0.48       201
          19       0.64      0.36      0.46       201
          20       0.16      0.79      0.26       200
          21       0.68      0.52      0.59       201
          22       0.36      0.33      0.35       201
          23       0.56      0.68      0.61       201
          24       0.66      0.64      0.65       201
          25       0.78      0.54      0.64       201
          26       0.41      0.46      0.43       201
          27       0.51      0.09      0.16       201
          28       0.49      0.36      0.41       201
          29       0.57      0.32      0.41       201
          30       0.60      0.58      0.59       200

    accuracy                           0.45      6225
   macro avg       0.52      0.45      0.46      6225
weighted avg       0.52      0.45      0.46      6225

In [74]:
x_test[:5]

47880     Glue Sticks Are The Secret Brow Tool You've Be...
119309    Secrets of Power: The Lesson of Five Chilean P...
94208     The Prophet of "Jordan's Mists" The sun comes ...
111233    The Resume Secret It Takes A Lifetime To Learn...
22621     As A Childfree Woman, Every Day Is Independenc...
Name: text, dtype: object

In [75]:
y_test[:5]

47880      7
119309     5
94208      4
111233    20
22621     22
Name: category_num, dtype: int64

In [76]:
y_pred[:5]

array([20,  5, 15, 20, 20])

In [77]:
df_balanced['preproced_txt'] = df_balanced.text.apply(preprocess)

In [78]:
df_balanced.head()

,short_description,headline,date,link,authors,category,category_num,text,preproced_txt
121346,,High School Dropout Rate: Solutions for Success,2014-06-01,https://www.huffingtonpost.com/entry/high-scho...,"Matthew Lynch, Ed.D., ContributorAuthor of The...",EDUCATION,0,High School Dropout Rate: Solutions for Success,High School Dropout rate solution success
107716,There is a solid base of evidence that we can ...,Can We Learn to Get Along?,2014-11-02,https://www.huffingtonpost.com/entry/can-we-le...,"Fernando Reimers, ContributorAcademic and Advi...",EDUCATION,0,Can We Learn to Get Along? There is a solid ba...,learn solid base evidence draw support educati...
120348,Lengthening the tenure decision process from t...,Vergara v. California Decision: Teacher Tenure...,2014-06-12,https://www.huffingtonpost.com/entry/vergara-v...,"Erin Simmeth, ContributorPublic school teacher...",EDUCATION,0,Vergara v. California Decision: Teacher Tenure...,Vergara v. California decision teacher tenure ...
98572,Technology has become further integrated into ...,The Global Search for Education: The Tech Repo...,2015-02-16,https://www.huffingtonpost.com/entry/the-globa...,"C. M. Rubin, ContributorBlogger and author, 'T...",EDUCATION,0,The Global Search for Education: The Tech Repo...,Global Search Education Tech Report Australia ...
93193,Hillary Clinton may need to school herself a b...,Hillary Clinton Feels Common Core Pain,2015-04-19,https://www.huffingtonpost.com/entry/hillary-c...,"Anthony Cody, ContributorCo-Founder, Network f...",EDUCATION,0,Hillary Clinton Feels Common Core Pain Hillary...,Hillary Clinton feel Common Core Pain Hillary ...

In [80]:
X_train, X_test, y_train, y_test = train_test_split(
    df_balanced.preproced_txt, 
    df_balanced.category_num, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df_balanced.category_num
)

In [81]:
clf = Pipeline([
    ('vectorizer_bow', CountVectorizer(ngram_range = (1, 2))),        #using the ngram_range parameter 
    ('Multi NB', MultinomialNB())
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.45      0.74      0.56       201
           1       0.28      0.46      0.34       201
           2       0.42      0.56      0.48       201
           3       0.69      0.45      0.54       201
           4       0.65      0.47      0.55       200
           5       0.67      0.46      0.54       201
           6       0.42      0.39      0.41       201
           7       0.73      0.43      0.54       200
           8       0.44      0.30      0.36       201
           9       0.50      0.50      0.50       201
          10       0.42      0.49      0.46       201
          11       0.44      0.42      0.43       201
          12       0.46      0.39      0.42       200
          13       0.44      0.40      0.42       201
          14       0.50      0.37      0.43       200
          15       0.61      0.59      0.60       201
          16       0.63      0.63      0.63       201
          17       0.68      0.56      0.62       201
          18       0.47      0.54      0.50       201
          19       0.66      0.42      0.52       201
          20       0.22      0.68      0.33       200
          21       0.70      0.61      0.65       201
          22       0.45      0.33      0.38       201
          23       0.53      0.70      0.60       201
          24       0.67      0.72      0.69       201
          25       0.68      0.59      0.63       201
          26       0.43      0.42      0.42       201
          27       0.41      0.12      0.19       201
          28       0.45      0.39      0.42       201
          29       0.51      0.37      0.43       201
          30       0.58      0.62      0.60       200

    accuracy                           0.49      6225
   macro avg       0.52      0.49      0.49      6225
weighted avg       0.52      0.49      0.49      6225

In [82]:
x_test[:5]

47880     Glue Sticks Are The Secret Brow Tool You've Be...
119309    Secrets of Power: The Lesson of Five Chilean P...
94208     The Prophet of "Jordan's Mists" The sun comes ...
111233    The Resume Secret It Takes A Lifetime To Learn...
22621     As A Childfree Woman, Every Day Is Independenc...
Name: text, dtype: object

In [83]:
y_test[:5]

47880      7
119309     5
94208      4
111233    20
22621     22
Name: category_num, dtype: int64

In [85]:
y_pred[:5]

array([ 7,  5, 15, 20, 20])